name: Deploy Landing Page
# Needs to enable `pages` in the repo settings first, free only for public repos

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy-landing-page:
    name: Deploy Landing Page
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: landing_page

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
